# Generated by Django 4.1.3 on 2023-12-03 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=10)),
                ('emailid', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(max_length=10)),
                ('mother_name', models.CharField(max_length=50)),
                ('address_landmark', models.CharField(max_length=50)),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=50)),
                ('address_pincode', models.CharField(max_length=10)),
                ('loan_type', models.CharField(max_length=15)),
                ('pancard', models.CharField(max_length=30)),
                ('aadhar', models.CharField(max_length=30)),
                ('loan_amount', models.CharField(max_length=10)),
                ('deposite_period', models.CharField(max_length=5)),
                ('bank_name', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=25)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
